import Head from 'next/head'
import Link from 'next/link'

export default function Header() {
    return (
        <header>
          <Head>
            <title>Anfaa | Lembaga Amil Zakat</title>
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/assets/images/icon.ico" />
            {/* Bundle Bootstrap 5 --> */}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" Crossorigin="anonymous"></script>
          </Head>

          {/* Navbar */}
          <nav className="navbar navbar-expand-lg navbar-light px-5">
            <Link href='/' passHref>
              <a className="navbar-brand">Anfaa</a>
            </Link>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarText">
              <ul className="navbar-nav mx-auto">
                <li className="nav-item">
                  <Link href="/#profil">
                    <a className="nav-link">Profil</a>
                  </Link>
                </li>
                <li className="nav-item">
                  <Link href="/#program">
                    <a className="nav-link">Program</a>
                  </Link>
                </li>
                <li className="nav-item">
                  <Link href="/#layanan">
                    <a className="nav-link">Layanan</a>
                  </Link>
                </li>
              </ul>
              <Link href="/berita">
                <a>
                  <span className="btn btn-success px-4 btn-berita">
                    Berita
                  </span>
                </a>
              </Link>
            </div>
          </nav>
        </header>
    )
}
